version: "3.7"
services:
  adminer:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:adminer.${STACK_DOMAIN},adminer.${STACK_DOMAIN_LOCAL}
      - traefik.port=8080
    image: "adminer:4@sha256:4ca2a6eb39e94af14d317232e86855c8fc442c3d5332fab9ce70d0bc3b112d65"
  drinks-touch:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${STACK_DOMAIN},${STACK_DOMAIN_LOCAL},www.${STACK_DOMAIN},www.${STACK_DOMAIN_LOCAL}
      - traefik.port=80
    environment:
      DISPLAY: "unix${DISPLAY}"
    image: "flipdot/drinks-touch:dev"
    volumes:
    - "../../drinks-touch/drinks_touch/:/app/"
    - "/tmp/.X11-unix:/tmp/.X11-unix"
  ldap:
    image: "osixia/openldap@sha256:eaefde9d33b03fe04d081767fda7d3c3500ec861108bbdd19c1b5ceb76e3ee27"
    environment:
      LDAP_DOMAIN: "flipdot.org"
      LDAP_LOGIN_DN: "dc=flipdot,dc=org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
    - "389:389"
    - "639:639"
  phpldapadmin:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:phpldapadmin.${STACK_DOMAIN},phpldapadmin.${STACK_DOMAIN_LOCAL}
      - traefik.port=6443
    environment:
      PHPLDAPADMIN_HTTPS: "true"
    image: "osixia/phpldapadmin:0.9.0@sha256:0b1e0ac15fff82dc5fdf12be6de06f91dc97f5fc95df5a29422a4b168dd818a6"
    volumes:
    - "phpldapadmin-data:/var/www/phpldapadmin"
  postgres:
    image: "postgres:12.0-alpine@sha256:55ce4ed5ea366bfe9bd141b85608eb62a9f26f524ce0d095fb4c0a3ee50228cd"
    environment:
      POSTGRES_DB: "drinks"
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
    - "../production/data/postgres/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql"
    - "../production/data/postgres/02-drinks.sql:/docker-entrypoint-initdb.d/02-drinks.sql"
  traefik:
    command:
    - --api
    - --defaultentrypoints=http,https
    - --docker
    - --docker.exposedByDefault=false
    - --docker.swarmMode=true
    - --entryPoints=Name:http Address::80
    - --entryPoints=Name:https Address::443 TLS:/etc/traefik/acme/drinks-touch.crt,/etc/traefik/acme/drinks-touch.key
      Compress:true
    - --insecureSkipVerify=true
    deploy:
      labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.${STACK_DOMAIN},traefik.${STACK_DOMAIN_LOCAL}
      - traefik.port=8080
      mode: global
      placement:
        constraints:
        - node.role == manager
    image: traefik:1.7-alpine@sha256:b21fa147641d99b470d70a4197bc4f6ca460d52a48eca2e9d4fa8df548db60d5
    ports:
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./certificates/:/etc/traefik/acme/
volumes:
  phpldapadmin-data: {}
  postgres-data: {}
