services:
  drinks-touch:
    image: flipdot/drinks-touch:0.1.1
  ldap: (( prune ))
  phpldapadmin: (( prune ))
  postgres: (( prune ))
  traefik:
    volumes:
    - (( replace ))
    - /var/run/docker.sock:/var/run/docker.sock
    - acme_data:/etc/traefik/acme/
volumes:
  acme_data: {}
  postgres-data: (( prune ))