services:
  drinks-touch:
    environment:
      ENV: "PI"
    image: flipdot/drinks-touch:0.1.2
  ldap: (( prune ))
  phpldapadmin: (( prune ))
  postgres: (( prune ))
  reset-touch:
    environment:
      DISPLAY: "unix${DISPLAY}"
    image: "flipdot/reset-touch:0.0.1"
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
  traefik:
    command:
    - (( prepend ))
    - --acme.acmeLogging=true
    - --acme.httpChallenge.entrypoint=http
    - --acme.domains=${STACK_DOMAIN}
    - --acme.email=${STACK_ACME_EMAIL}
    - --acme.entrypoint=https
    - --acme.storage=/etc/traefik/acme/acme.json
    volumes:
    - (( replace ))
    - /var/run/docker.sock:/var/run/docker.sock
    - acme_data:/etc/traefik/acme/
  traefik_certs-dumper:
    image: ldez/traefik-certs-dumper:v2.4.0
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --post-hook=/mnt/traefik_certs-dumper/post-hook $STACK_DOMAIN
    - --source=/etc/traefik/acme/acme.json
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    volumes:
    - acme_data:/etc/traefik/acme/
    - ./configurations/traefik_certs-dumper/post-hook:/mnt/traefik_certs-dumper/post-hook
volumes:
  acme_data: {}
  postgres-data: (( prune ))