services:
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  drinks-touch:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.drinks-touch_secure.tls.certresolver=default
    environment:
      ENV: PI
    image: flipdot/drinks-touch:0.2.0@sha256:1ea32d4e2d3a6a713805f4f6155ed775966b2a58c39a24f6e2582c4fbde213cb
  ldap: (( prune ))
  phpldapadmin: (( prune ))
  postgres: (( prune ))
  reset-touch:
    environment:
      DISPLAY: unix${DISPLAY}
    image: flipdot/reset-touch:0.0.1@sha256:165529304d24c14b8aa5e4e12430f7750704828e09c1a1aecbfa4096d4843be7
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.0@sha256:63614a85fe984b62716c638bca1a0a837e86f7249ef3c0e7f9db8a1fed743c96
    volumes:
    - acme_data:/etc/traefik/acme/
volumes:
  acme_data: {}
  postgres-data: (( prune ))